name: Build Standalone Executables

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable with PyInstaller
      run: |
        if [ $RUNNER_OS == "Windows" ]; then
          # Для Windows используем --onefile и --icon
          pyinstaller --onefile --name "CortexDevAnalyzer" --icon "icon.ico" cortex-dev-analyzer.py
        elif [ $RUNNER_OS == "macOS" ]; then
          # Для macOS убираем --onefile и добавляем --windowed для создания .app бандла
          pyinstaller --windowed --name "CortexDevAnalyzer" --icon "icon.icns" cortex-dev-analyzer.py
        else
          # Для Linux --onefile остается лучшим вариантом
          pyinstaller --onefile --name "CortexDevAnalyzer" cortex-dev-analyzer.py
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: CortexDevAnalyzer-${{ runner.os }}
        path: dist/*